### ISSUE TITLE
DB connection drops after being idle and error kills application

### ISSUE THREAD

**Issue by khalathas** [khalathas/rpgtools-api#4]
Leaving the app running idle for an extended period of time, I got error:
> events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/raistlin/development/rpgtools-api/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/raistlin/development/rpgtools-api/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleNetworkError (/home/raistlin/development/rpgtools-api/node_modules/mysql/lib/protocol/Protocol.js:371:10
    at Connection._handleNetworkError (/home/raistlin/development/rpgtools-api/node_modules/mysql/lib/Connection.js:418:18)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true
}

Likely need to either more gracefully handle a connection reset to prevent crash, or figure out if this is normal or a system problem.
Notable info, was running the app on my server over mobaxterm SSH, and moba may have idled as well.  Might be better to run in screen detached.

**Comment by khalathas** [comment]
Confirmed, root cause is that mysql server is closing the connection after the idle timeout.  Connection pools handle these connect/disconnect events gracefully.
